name: Mobile testing
on:
  push:
    branches:
      - main

jobs:
  mobile_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Run tests on Pixel 3a
        run: npm run pixel3a.ci
        env:
          USER: ${{ secrets.SECRET_USER }}
          KEY: ${{ secrets.SECRET_KEY }}

      - name: Run tests on Pixel 7 Pro
        run: npm run pixel7pro.ci
        env:
          USER: ${{ secrets.SECRET_USER }}
          KEY: ${{ secrets.SECRET_KEY }}
